### ISSUE TITLE
Comments go missing if time hasn't changed

### ISSUE THREAD

**Issue by redxeth** [Origen-SDK/origen_sim#8]
If you do multiple comments before a cycle occurs-- then it outputs only the very last one. 

`ss 'Comment A'`
`ss 'Comment B'`

This happens a lot without realizing it when adding comment output to functions that are nested within each other.

We should prob update it to concatenate several comments together -- so they all occur at the same 'time' but you still can see them.   

Perhaps resulting in something like this:

'Comment A - Comment B'

**Comment by ginty** [comment]
Thanks for reporting this @redxeth.

I think its better to handle as much of this at possible at the Origen level and only push down the simulator where necessary.

With that in mind, do you fancy looking at a fix whereby the comments are buffered instead of being applied to the simulator directly - https://github.com/Origen-SDK/origen_sim/blob/master/lib/origen_sim/tester.rb#L66

And then the buffer is flushed before issuing a cycle here - https://github.com/Origen-SDK/origen_sim/blob/master/lib/origen_sim/tester.rb#L58

**Comment by redxeth** [comment]
@ginty thanks.  Seems could be fixed at the simulator level.  Why fix at Origen level?   This way any user of simulator will not see issue with comments (if they use directly).

**Comment by ginty** [comment]
Generally we want to keep most of the intelligence at the Origen level (i.e. in Ruby code) rather than at simulator level (i.e. in C code).
I don't really understand your second sentence, did you think I meant Origen core by Origen-level perhaps?

The benefits of keeping everything in Ruby instead of C where possible are:

- If its in Ruby it can be enhanced and fixed (if there is a bug) in future and immediately roll out. If it is in C, then all the design snapshots would need to be recompiled with the new C extension to pick it up.

- Everyone who contributes to Origen is comfortable in the Ruby space, not so true for the C/simulator space.

**Comment by ginty** [comment]
For comparison, this is where you would have to look to fix it at the C/simulator-level - https://github.com/Origen-SDK/origen_sim/blob/master/ext/bridge.c#L690

**Comment by redxeth** [comment]
I was thinking to update simulator.rb in origen_sim to just concatenate the string before calling the lower level C code stuff.

**Comment by ginty** [comment]
That's fine, I don't see much difference between adding it to simulator.rb vs. tester.rb like I proposed.

**Comment by ginty** [comment]
Fixed by #24
